public static class GeographyMapping
{
    public static readonly Dictionary<string, string> CountryISO2CodeToContinent = new()
    {
        { "AF", "Asia" },
        { "AL", "Europe" },
        { "AD", "Europe"},
        { "AM", "Asia" },
        { "AO", "Africa" },
        { "AR", "South America" },
        { "AT", "Europe" },
        { "AU", "Oceania" },
        { "AG", "North America"},
        { "AZ", "Asia" },
        { "AE", "Asia" },
        { "BA", "Europe" },
        { "BB", "North America" },
        { "BD", "Asia" },
        { "BE", "Europe" },
        { "BF", "Africa" },
        { "BG", "Europe" },
        { "BH", "Asia" },
        { "BI", "Africa" },
        { "BJ", "Africa" },
        { "BN", "Asia" },
        { "BO", "South America" },
        { "BR", "South America" },
        { "BS", "North America" },
        { "BT", "Asia" },
        { "BW", "Africa" },
        { "BY", "Europe" },
        { "BZ", "North America" },
        { "CA", "North America" },
        { "CD", "Africa" },
        { "CF", "Africa" },
        { "CG", "Africa" },
        { "CH", "Europe" },
        { "CI", "Africa" },
        { "CL", "South America" },
        { "CM", "Africa" },
        { "CN", "Asia" },
        { "CO", "South America" },
        { "CR", "North America" },
        { "CU", "North America" },
        { "CV", "Africa" },
        { "CY", "Asia" },
        { "CZ", "Europe" },
        { "DE", "Europe" },
        { "DJ", "Africa" },
        { "DK", "Europe" },
        { "DM", "North America" },
        { "DO", "North America" },
        { "DZ", "Africa" },
        { "EC", "South America" },
        { "EE", "Europe" },
        { "EG", "Africa" },
        { "ER", "Africa" },
        { "ES", "Europe" },
        { "ET", "Africa" },
        { "FI", "Europe" },
        { "FJ", "Oceania" },
        { "FM", "Oceania" },
        { "FR", "Europe" },
        { "GA", "Africa" },
        { "GB", "Europe" },
        { "GD", "North America" },
        { "GE", "Asia" },
        { "GH", "Africa" },
        { "GM", "Africa" },
        { "GN", "Africa" },
        { "GQ", "Africa" },
        { "GR", "Europe" },
        { "GT", "North America" },
        { "GW", "Africa" },
        { "GY", "South America" },
        { "HN", "North America" },
        { "HR", "Europe" },
        { "HT", "North America" },
        { "HU", "Europe" },
        { "ID", "Asia" },
        { "IE", "Europe" },
        { "IL", "Asia" },
        { "IN", "Asia" },
        { "IQ", "Asia" },
        { "IR", "Asia" },
        { "IS", "Europe" },
        { "IT", "Europe" },
        { "JM", "North America" },
        { "JO", "Asia" },
        { "JP", "Asia" },
        { "KE", "Africa" },
        { "KG", "Asia" },
        { "KH", "Asia" },
        { "KI", "Oceania" },
        { "KM", "Africa" },
        { "KN", "North America" },
        { "KP", "Asia" },
        { "KR", "Asia" },
        { "KW", "Asia" },
        { "KZ", "Asia" },
        { "XK", "Europe"},
        { "LA", "Asia" },
        { "LB", "Asia" },
        { "LC", "North America" },
        { "LI", "Europe" },
        { "LK", "Asia" },
        { "LR", "Africa" },
        { "LS", "Africa" },
        { "LT", "Europe" },
        { "LU", "Europe" },
        { "LV", "Europe" },
        { "LY", "Africa" },
        { "MA", "Africa" },
        { "MC", "Europe" },
        { "MD", "Europe" },
        { "ME", "Europe" },
        { "MG", "Africa" },
        { "MH", "Oceania" },
        { "MK", "Europe" },
        { "ML", "Africa" },
        { "MM", "Asia" },
        { "MN", "Asia" },
        { "MR", "Africa" },
        { "MT", "Europe" },
        { "MU", "Africa" },
        { "MV", "Asia" },
        { "MW", "Africa" },
        { "MX", "North America" },
        { "MY", "Asia" },
        { "MZ", "Africa" },
        { "NA", "Africa" },
        { "NE", "Africa" },
        { "NG", "Africa" },
        { "NI", "North America" },
        { "NL", "Europe" },
        { "NO", "Europe" },
        { "NP", "Asia" },
        { "NR", "Oceania" },
        { "NZ", "Oceania" },
        { "OM", "Asia" },
        { "PS", "Asia"},
        { "PA", "North America" },
        { "PE", "South America" },
        { "PG", "Oceania" },
        { "PH", "Asia" },
        { "PK", "Asia" },
        { "PL", "Europe" },
        { "PT", "Europe" },
        { "PW", "Oceania" },
        { "PY", "South America" },
        { "QA", "Asia" },
        { "RO", "Europe" },
        { "RS", "Europe" },
        { "RU", "Europe" },
        { "RW", "Africa" },
        { "SA", "Asia" },
        { "SB", "Oceania" },
        { "SC", "Africa" },
        { "SD", "Africa" },
        { "SE", "Europe" },
        { "SG", "Asia" },
        { "SI", "Europe" },
        { "SK", "Europe" },
        { "SL", "Africa" },
        { "SM", "Europe" },
        { "SN", "Africa" },
        { "SO", "Africa" },
        { "SR", "South America" },
        { "SS", "Africa" },
        { "ST", "Africa" },
        { "SV", "North America" },
        { "SY", "Asia" },
        { "SZ", "Africa" },
        { "TW", "Asia"},
        { "TD", "Africa" },
        { "TG", "Africa" },
        { "TH", "Asia" },
        { "TJ", "Asia" },
        { "TL", "Asia" },
        { "TM", "Asia" },
        { "TN", "Africa" },
        { "TO", "Oceania" },
        { "TR", "Asia" },
        { "TT", "North America" },
        { "TV", "Oceania" },
        { "TZ", "Africa" },
        { "UA", "Europe" },
        { "UG", "Africa" },
        { "US", "North America" },
        { "UY", "South America" },
        { "UZ", "Asia" },
        { "VA", "Europe" },
        { "VC", "North America" },
        { "VE", "South America" },
        { "VN", "Asia" },
        { "VU", "Oceania" },
        { "WS", "Oceania" },
        { "YE", "Asia" },
        { "ZA", "Africa" },
        { "ZM", "Africa" },
        { "ZW", "Africa" }
    };

    public static string GetContinent(string countryISO2Code)
    {
        return CountryISO2CodeToContinent.TryGetValue(countryISO2Code, out var continent)
        ? continent
        : "Unknown";
    }
}